# Preface {.unnumbered}

Thse notes are divided into 5 parts

- Probability
- Statistics
- Supervised machine learning
- Unsupervised machine learning
- Computing frameworks

The notes are compiled with <a href="https://jupyter.org/>Jupyter lab</a>.
Throughout these notes I am using Python and its data science related packages such as

- <a herf="https://scikit-learn.org/stable/index.html">scikit-learn</a>
- <a href="https://pandas.pydata.org/">Pandas</a>
- <a href="https://matplotlib.org/">matplotlib</a>
- <a href="https://numpy.org/">numpy</a>

When looking into the computing frameworks part of the notes, I will use

- <a href="#">Apache Spark</a>
- <a href="#">PyTorch</a>

You can use  <https://quarto.org/docs/books>Quarto</a> in order to compile the
Jupyter notebooks into an e-book. To learn more about Quarto books visit <https://quarto.org/docs/books>.

The notes have been developed by using various resources and references the main ones are listed in the references.

## References & Resources



### Books for Python programming

- <a href="https://python-3-patterns-idioms-test.readthedocs.io/en/latest/index.html">Python 3 Patterns, Recipes and Idioms</a>
- <a href="https://leanpub.com/clean-architectures-in-python">Clean Architectures in Python</a>
- <a href="https://automatetheboringstuff.com/">Automate the Boring Stuff with Python</a>


### Books for Machine Learning and Statistics with Python

- https://jakevdp.github.io/PythonDataScienceHandbook/
- Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani, Jonathan Taylor, _An Introduction to Statistical Learning_, 2nd Edition, Springer, 2021 (available at https://www.statlearning.com/?utm_source=substack&utm_medium=email).

